name: CI

on: [push, pull_request]

env:
  YARN_NODE_LINKER: pnp # use pnp linker for better linking performance
  YARN_ENABLE_SCRIPTS: false # disable post-install scripts

jobs:
  prepare-yarn-cache:
    name: Prepare Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js latest
        uses: actions/setup-node@v2-beta
        with:
          node-version: "*"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-
      - name: Check Yarn dedupe
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn dedupe --check
      - name: Check or update Yarn cache
        env:
        run: |
          yarn install --immutable --skip-builds
  test:
    name: Test on Node.js # GitHub will add ${{ matrix.node-version }} to this title
    needs: prepare-yarn-cache
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ["*", 14, 12]
        os: ["ubuntu-latest", "windows-latest"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js latest # Run yarn on latest node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "*" # Build Babel on latest node LTS versions
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
      - name: Install
        run: |
          yarn install
      - name: Use Node.js ${{ matrix.node-version }} # Checkout node version for test executor
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test
        run: |
          yarn test --coverage
      - name: Coveralls GitHub Action
        if: matrix.node-version == '*'
        uses: coverallsapp/github-action@v1.1.2
